---
- name: Actualizar paquetes e instalar mariadb
  hosts: linux
  remote_user: ansible
  become: true
  tasks:
    - name: Upgrade repositorios
      ansible.builtin.include_tasks: modulos/actualizarPaquetes.yml
  
    - name: Instalar MariaDB
      ansible.builtin.include_tasks: modulos/instalarMariaDB.yml

    - name: Configurar servicio mariadb
      ansible.builtin.include_tasks: modulos/configurarServicioMariaDB.yml

- name: Configuracion inicial y creacion de BD en mariadb Ubuntu
  hosts: linux
  remote_user: ansible
  gather_facts: false
  become: true
  tasks:

    - name: AÃ±adir .my.cnf
      template:
        src: credenciales/my.cnf
        dest: /home/ansible/.my.cnf
      when: ansible_facts['distribution'] == "Ubuntu"
      
    - name: Ensure root user can only login from localhost
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ mariadb_root_password }}"
        check_implicit_admin: yes
        name: root
        host: "{{ item }}"
        password: "{{ mariadb_root_password }}"
        state: present
      with_items:
        - localhost
        - 127.0.0.1
        - ::1
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Ensure root user can only login from localhost
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_password: "{{ mariadb_root_password }}"
        check_implicit_admin: yes
        name: root
        host: "{{ item }}"
        password: "{{ mariadb_root_password }}"
        state: present
      with_items:
        - localhost
        - 127.0.0.1
        - ::1
      when: ansible_facts['distribution'] == "Rocky"

    - name: Reload privilege tables
      command: |
        mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: Remove anonymous users
      command: |
        mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
      with_items:
        - DELETE FROM mysql.user WHERE User=''
      changed_when: False

    - name: Disallow root login remotely
      command: |
        mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: False

    - name: Remove test database and access to it
      command: |
        mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
      with_items:
        - DROP DATABASE IF EXISTS test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False

    - name: Crear base de datos para proyecto
      command: |
        mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
      with_items:
        - CREATE DATABASE BD_HERNESTO
      changed_when: False

    - name: Reload privilege tables
      command: |
        mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: Borrar .my.conf
      file:
        path: /home/ansible/.my.cnf
        state: absent

# - name: Configuracion inicial y creacion de BD en mariadb Rocky
#   hosts: rocky
#   remote_user: ansible
#   gather_facts: false
#   become: true
#   tasks:

#     - name: Ensure root user can only login from localhost
#       mysql_user:
#         login_password: "{{ mariadb_root_password }}"
#         check_implicit_admin: yes
#         name: root
#         host: "{{ item }}"
#         password: "{{ mariadb_root_password }}"
#         state: present
#       with_items:
#         - localhost
#         - 127.0.0.1
#         - ::1

#     - name: Reload privilege tables
#       command: |
#         mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
#       with_items:
#         - FLUSH PRIVILEGES
#       changed_when: False

#     - name: Remove anonymous users
#       command: |
#         mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
#       with_items:
#         - DELETE FROM mysql.user WHERE User=''
#       changed_when: False

#     - name: Disallow root login remotely
#       command: |
#         mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
#       with_items:
#         - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
#       changed_when: False

#     - name: Remove test database and access to it
#       command: |
#         mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
#       with_items:
#         - DROP DATABASE IF EXISTS test
#         - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
#       changed_when: False

#     - name: Crear base de datos para proyecto
#       command: |
#         mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
#       with_items:
#         - CREATE DATABASE BD_HERNESTO
#       changed_when: False

#     - name: Reload privilege tables
#       command: |
#         mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
#       with_items:
#         - FLUSH PRIVILEGES
#       changed_when: False

#     - name: Borrar .my.conf
#       file:
#         path: /home/ansible/.my.cnf
#         state: absent
