---
- name: Instalacion y configuraci√≥n de mariadb server
  hosts: linux
  remote_user: ansible
  become: true
  tasks:
  
    - name: Upgrade repositorios
      ansible.builtin.include_tasks: ../tasks/mariadb/actualizarPaquetes.yml
  
    - name: Instalar MariaDB
      ansible.builtin.include_tasks: ../tasks/mariadb/instalarMariaDB.yml

    - name: Configurar servicio mariadb
      ansible.builtin.include_tasks: ../tasks/mariadb/configurarServicioMariaDB.yml

    - name: Configurar mariadb
      ansible.builtin.include_tasks: ../tasks/mariadb/configuracionInicialMariaDB.yml